### ISSUE TITLE
NotebookSpecs fail

### ISSUE THREAD

**Issue by watercrossing** [wolfe-pack/wolfe#128]
On my machine, `ml.wolfe.ui.NotebookSpecs` fail:
```
[info] NotebookSpecs:
[info] A code block source generator
[info] - should return the source string corresponding to the block *** FAILED ***
[info]   "val i = 5[
[info]   val j = 2]
[info]   i + j + 2" was not equal to "val i = 5[
]info]   val j = 2
[info]   i + j + 2" (NotebookSpecs.scala:18)
```
This occurs with a clean git pull. The only differences my setup has to Travis is I am running windows 8.1 and java 1.8.0_25 (travis uses java 1.7). Any idea why this happens?

Append:
I just tried java 1.7.0_71, and it fails too. Might this be a Windows related issue o_O?

**Comment by riedelcastro** [comment]
This is not needed anymore, so I removed it.
