### ISSUE TITLE
Symbolic link function creates a hard link

### ISSUE THREAD

**Issue by mayhewsw** [wolfe-pack/wolfe#131]
In the wolfe-util package, [package.scala](https://github.com/wolfe-pack/wolfe/blob/dev/wolfe-util/src/main/scala/ml/wolfe/util/package.scala) in particular, it appears that the `createSymbolicLinkToLatest()` function attempts to create a hard link to a folder. On my OS (Scientific Linux), this is not permitted. 

Shouldn't the function be [`Files.createSymbolicLink`](http://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#createSymbolicLink(java.nio.file.Path,%20java.nio.file.Path,%20java.nio.file.attribute.FileAttribute...))?

**Comment by watercrossing** [comment]
You are correct. Fixed by 2d25f2c4f0db2155577e425a3848849da1c674de.
