### ISSUE TITLE
Linear Chain example fails

### ISSUE THREAD

**Issue by watercrossing** [wolfe-pack/wolfe#134]
https://github.com/wolfe-pack/wolfe/blob/dev/wolfe-examples/src/main/scala/ml/wolfe/examples/LinearChain.scala fails with the error message:

    Exception in thread "main" java.lang.Error: Method copy not defined on class cc.factorie.la.SingletonTensor1
    	at cc.factorie.la.Tensor1$class.copy(Tensor1.scala:63)

It seems like we are using a SingletonTensor in an unsupported way?

**Comment by riedelcastro** [comment]
Yep, need to create our own copy around it for now. Note this linear chain representation is deprecated in that now we have variable length sequence domains that allow us to use the same domain across several instances. This allows to use same term (and memory allocation) for all instances in the corpus, which makes things more memory and cpu efficient

**Comment by riedelcastro** [comment]
I think this outdated now, but I will create a related issue
