### ISSUE TITLE
Matrix Factorization Model Wrapper

### ISSUE THREAD

**Issue by riedelcastro** [wolfe-pack/wolfe#140]
In the spirit of the linear classifier and linear chain interfaces, which hide some of the Wolfe term and domain internals, it would be good to have a similar thing for matrix factorization.

**Comment by rockt** [comment]
Do you think our *Tensor* data structure and it's sampling mechanisms should go in there as well?

**Comment by riedelcastro** [comment]
I am wondering if it could be a simpler, possibly immutable representation of the tensor, to keep the complexity of this low.

**Comment by rockt** [comment]
Done with an initial version of it... can be made prettier though. Next, use this for a spec that fails once MF doesn't work anymore.

**Comment by riedelcastro** [comment]
Cool! Looks nice, we can iterate on this. One step could be to get rid of
the *var* thetaStar, and use the style of the linear classifier where theta
star is mixed in, either learned, or loaded. The other step is replacing
the Predictor logic with the fun(...) method as used in the other examples.

**Comment by rockt** [comment]
Like [this](https://github.com/wolfe-pack/wolfe/blob/63256c5360ee716dc5f22f8e11b0c95676ba155e/wolfe-examples/src/main/scala/ml/wolfe/model/MatrixFactorization.scala#L87-L89)?
