### ISSUE TITLE
Rename (and move) TermImplicits

### ISSUE THREAD

**Issue by riedelcastro** [wolfe-pack/wolfe#148]
@rockt @sameersingh For the release I wonder whether TermImplicits should become "Wolfe" and maybe be moved to ml.wolfe (from term)? The reason is that this is the main entry point to Wolfe, and almost every application of Wolfe will have this import. I think starting each wolfe program with

```scala
import ml.wolfe.Wolfe._
```

Alternatively we could move implicits into the wolfe package object? so it would become

```scala
import ml.wolfe._
```

But note that this would mean that each class within ml.wolfe gets these implicits automatically. It also feels a bit more like a normal package import that people may have different expectations for. Thoughts?

**Comment by sameersingh** [comment]
How about just `Implicits` just to be more, uhh, explicit?

Otherwise `ml.wolfe._` works better I think, since if we want it to be magic, let's let it be magic 😄

**Comment by riedelcastro** [comment]
`ml.wolfe.Implicits._` or `ml.wolfe.term.Implicits`?

**Comment by sameersingh** [comment]
Either works, but I meant (and prefer) `ml.wolfe.Implicits._`.

**Comment by riedelcastro** [comment]
Okay. Now that I am thinking about this, I may slightly prefer `wolfe.term.Implicits` because the implicits are really quite term specific (and, for example, do nothing with `wolfe.nlp`). If we think of wolfe primarily as the language, `wolfe.Implicits` makes sense though.

**Comment by rockt** [comment]
What about `ml.wolfe.Language`? But `ml.wolfe.Implicits` is fine with me too.

**Comment by riedelcastro** [comment]
I realized that the problem with Implicits is that not all of it is actually implicit (a lot functions that are directly called). `Language` could work!

**Comment by rockt** [comment]
What the... since when does closing issues with commit msg not work anymore?
