### ISSUE TITLE
Consistent Logging

### ISSUE THREAD

**Issue by riedelcastro** [wolfe-pack/wolfe#149]
We should have a consistent logging strategy (avoiding print statements). This may also help in conjunction with moro to show logging results somewhere on the moro screen. Any preferences and recommendations @rockt @sameersingh ?

**Comment by sameersingh** [comment]
I don't have a preference or recommendation, as long as mixing in a trait gives a logger we can call .info, .debug, etc. on, and switching log level along with picking a file to serialize to (as opposed to stdout) is as simple as including the info in a config file somewhere.

**Comment by riedelcastro** [comment]
Okay. @rockt, any recommendations? I guess we should use some standard architecture for this. Currently imported is 
```
    "com.typesafe.scala-logging" % "scala-logging-slf4j_2.11" % "2.1.2"
```
Probably fine. Question: things like the progress monitor, should they be written into the log stream?
S

**Comment by riedelcastro** [comment]
Okay, I am using `LazyLogging` of scala-logging-slf4j_2.11, which can be mixed in and then gives you a logger. ProgressBar now writes into the logging stream (I didn't get a veto/comment so I just went ahead).
