### ISSUE TITLE
Write Matrix/Vector wrapper classes

### ISSUE THREAD

**Issue by riedelcastro** [wolfe-pack/wolfe#161]
There exist several useful vector/matrix implementations in the java/scala universe, and depending on the use case we may need different ones. Also, there is currently a lot of code within `Settings` that performs different LA operations depending on the vector or matrix type. Both could be addressed by defining general Wolfe Vector and Matrix interfaces that wrap around specific Factorie, BidMat, Breeze etc implementations.

**Comment by rockt** [comment]
This will be addressed within the Tensor "wrapper".
