### ISSUE TITLE
Tutorial is down

### ISSUE THREAD

**Issue by omidb** [wolfe-pack/wolfe#163]
Hi guys,

I started from website and by clicking on tutorial I got into: 
http://moro.wolfe.ml:9000/template/wolfe/wolfe-docs/gettingstarted/01_welcome

which is not working.

Would you please fix it or let me know if I can run it locally?

**Comment by sameersingh** [comment]
Up again, thanks for reporting.

**Comment by omidb** [comment]
thanks

**Comment by omidb** [comment]
It's not working again!

**Comment by sameersingh** [comment]
Up again, but this time disabled code editing, since that's causing OOM on the server.

**Comment by sameersingh** [comment]
Added instructions to run this locally [here](https://github.com/wolfe-pack/moro/blob/master/README.md).
