### ISSUE TITLE
Term2LaTeX and Term2PrettyString

### ISSUE THREAD

**Issue by rockt** [wolfe-pack/wolfe#17]

**Comment by rockt** [comment]
Closed because `toPrettyString` is already being done for some terms and we will continue doing this where needed. Moreover, at some point we decided that `toLaTeX`might not be super useful.

**Comment by sameersingh** [comment]
Might be worth considering a simple toHtml, htmlgen style, for Moro and
otherwise.

**Comment by rockt** [comment]
I think something like a term tree visualization would be helpful. It could use htmlgen's `Graph`.

**Comment by riedelcastro** [comment]
I think a latex representation could actually make sense now (it would at least be much easier now). Term tree visualization would also be cool, I think theano and torch have stuff like that, no?

**Comment by sameersingh** [comment]
I think html one is the best for browsing since it can easily allow
interactive expansion. The theano ones I looked at were too nested to be
useful, even for simple factorization models.
