### ISSUE TITLE
Different ways of calculating Factorie differences lead to different results

### ISSUE THREAD

**Issue by riedelcastro** [wolfe-pack/wolfe#60]
In the GradientCalculator we can do (for two factorie sparse vectors `arg1` and `arg2`

```scala
arg1 - arg2
```
or 
```scala
val result = new cc.factorie.la.SparseTensor1(arg1.size + arg2.size)
result += arg1
result -= arg2
result
```

I'd expect the same solution after training, but we get different numbers. Debugging so far has shown that both sparse vectors have the same activeElements, but possibly different underlying elements.

**Comment by rockt** [comment]
Is this still an issues or has this been fixed by Factorie? Also, might not be relevant anymore once we switch to other LinAlg libraries.

**Comment by riedelcastro** [comment]
I don't think this was fixed, but it may not be relevant so let's close it and reopen if necessary.
